[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/results"
  to = "/results.html"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

[build.environment]
  NODE_VERSION = "18"
